### ISSUE TITLE
Bitnami's cert-manager does not includes some containers available at `jetstack/cert-manager`

### ISSUE THREAD

**Issue by jbianquetti-nami** [bitnami/bitnami-docker-cert-manager#2]
**Description**

Cert-manager includes 3 containers but Bitnami's container just one: the controller. 

**Steps to reproduce the issue:**

```
curl -Ls  https://github.com/jetstack/cert-manager/releases/download/v0.12.0/cert-manager.yaml | grep 'image: '
          image: "quay.io/jetstack/cert-manager-cainjector:v0.12.0"
          image: "quay.io/jetstack/cert-manager-controller:v0.12.0"
          image: "quay.io/jetstack/cert-manager-webhook:v0.12.0"
```
**Describe the results you received:**

Bitnami container just uses the controller. 

**Describe the results you expected:**

All containers for cert-manager are provided by Bitnami.

**Additional information you deem important (e.g. issue happens only occasionally):**

Maybe the container has been built using a `fat binary` which includes all them?

**Comment by javsalgar** [comment]
Hi,

I confirm that we only build the controller. We will open an internal task to evaluate packaging the rest of them.

**Comment by SimeonPoot** [comment]
> Hi,
> 
> I confirm that we only build the controller. We will open an internal task to evaluate packaging the rest of them.

Is there some insight in this internal task? e.g. When can we expect it? Thanks in advance

**Comment by javsalgar** [comment]
I'm afraid it is still in our backlog. Due to priorities we couldn't dedicate time to this yet. We cannot guarantee an ETA but we will update the ticket as soon as we have more news.

**Comment by alvneiayu** [comment]
hi all

Already released the bitnami containers for the [cainjector](https://github.com/bitnami/bitnami-docker-cainjector) and the [webhook](https://github.com/bitnami/bitnami-docker-cert-manager-webhook). Moreover, we have released a bitnami cert manager chart, [here](https://github.com/bitnami/charts/tree/master/bitnami/cert-manager).

Thanks for your patience. If I can help you with something else, let me know.

Álvaro
