### ISSUE TITLE
quay.io/jetstack/cert-manager-acmesolver:{STABLE_APP_VERSION}

### ISSUE THREAD

**Issue by SSchwaiger** [bitnami/bitnami-docker-cert-manager#4]
**Description**

I've migrated a cert-manager installation from bitnami/cert-manager:0.5.2-r37 to bitnami/cert-manager:0.13.1. Despite different configuration changes I had to make, I discovered that using the HTTP01 solver fails with the current Docker image (deployed into a Kubernetes cluster).

**Steps to reproduce the issue:**

1. start bitnami/cert-manager:0.13.1 Docker image

**Describe the results you received:**

The cm-acme-http-solver-* pods created by the controller have "{STABLE_APP_VERSION}" as revision and therefore fail to run.

Checking the controller logs files, I see the following message:

```
cert-manager "msg"="starting controller" "git-commit"="{STABLE_APP_GIT_COMMIT}" "version"="{STABLE_APP_VERSION}"
```

**Describe the results you expected:**

Correctly running HTTP01 challenge solvers.

Note: when I use the image quay.io/jetstack/cert-manager-controller:v0.13.1, it works fine.

**Comment by juan131** [comment]
Hi @SSchwaiger 

Could you please share the manifest you're using to deploy the `cert-manager` container on your K8s cluster? I'd like to reproduce the exact issue you're facing

**Comment by SSchwaiger** [comment]
Hi!

Those are the files I've used: https://github.com/SSchwaiger/base/tree/master/cert-manager
Basically, I took the templates from here https://cert-manager.io/docs/installation/kubernetes/

**Comment by juan131** [comment]
Hi @SSchwaiger 

You're right and we're not setting the version correctly when compiling the binary. I've fixed that in the latest version that was just released (`0.14.0`).

You can test it running the command below:

```console
$ docker run --rm bitnami/cert-manager:0.14.0
I0317 11:59:38.518975       1 start.go:76] cert-manager "msg"="starting controller"  "git-commit"="6da95758a4751b20cf85b29a3252e993449660eb" "version"="v0.14.0"
(...)
```

**Comment by SSchwaiger** [comment]
Thx a lot!

**Comment by juan131** [comment]
Thank you for reporting it!!! 😃
